### PR TITLE
refactor: rewrite using the builder pattern

### PR DESCRIPTION
**Pull request by liby**
## Motivation

https://github.com/spa5k/slugify-rs/pull/3#issuecomment-1182082778

## Benchmark

image

### CODE REVIEW

**Comment by spa5k** [comment]
is it already done? and just needs cleaning older code

**Comment by liby** [comment]
> is it already done? and just needs cleaning older code

Yes, it's ready! All that's left is a few detailed tweaks, such as using `SlugBuilder::new(text)` instead of the `slugify(text)` function(optional).

After that it is a matter of removing some macros and leaving only some necessary definitions.

Of course, some modifications are needed to support calling the current implementation that uses the builder pattern.

These are more or less involved in breaking change and personal preferences, and you can make your own choices.

**Comment by spa5k** [comment]
Will look into it during weekend

**Comment by spa5k** [comment]
I was thinking that making loads of variants of a single slug, we can simply create 2/3 sets of slugs.

Like

```rust
slugify!();
slugify_upper(); <-
slugify_lower(); <- Not this one and the above one tho
slugify_l(); <- for custom length
```

**Comment by spa5k** [comment]
hey @liby can you finish this whole PR, we will just do the major release, sorry not getting much time these days to do anything.

**Review by spa5k — APPROVED** [review]

**Comment by spa5k** [comment]
Will add more stuff and clean it after merging it. @liby contribute if you want since you know more about this pattern.

**Pull request merged**
